/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_hescoded_devmangala_game_NativeEngine */

#ifndef _Included_me_hescoded_devmangala_game_NativeEngine
#define _Included_me_hescoded_devmangala_game_NativeEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_hescoded_devmangala_game_NativeEngine
 * Method:    findBestMove
 * Signature: ([IIZ)[I
 */
JNIEXPORT jintArray JNICALL Java_me_hescoded_devmangala_game_NativeEngine_findBestMove
  (JNIEnv *, jobject, jintArray, jint, jboolean);

/*
 * Class:     me_hescoded_devmangala_game_NativeEngine
 * Method:    stopSearch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_hescoded_devmangala_game_NativeEngine_stopSearch
  (JNIEnv *, jobject);

/*
 * Class:     me_hescoded_devmangala_game_NativeEngine
 * Method:    startSearch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_hescoded_devmangala_game_NativeEngine_startSearch
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
